[tool.towncrier]
# Read https://github.com/ethereum/trin/newsfragments/README.md for instructions
package = "trin"
filename = "docs/release_notes.md"
directory = "newsfragments"
underlines = ["", ""]
issue_format = "[#{issue}](https://github.com/ethereum/trin/issues/{issue})"
start_string = "[//]: # (towncrier release notes start)"
title_format = "## {version} ({project_date})"

[[tool.towncrier.type]]
directory = "added"
name = "### Features"
showcontent = true

[[tool.towncrier.type]]
directory = "changed"
name = "### Changed Functionality"
showcontent = true

[[tool.towncrier.type]]
directory = "deprecated"
name = "### Soon-to-be Removed Features"
showcontent = true

[[tool.towncrier.type]]
directory = "removed"
name = "### Removed Features"
showcontent = true

[[tool.towncrier.type]]
directory = "fixed"
name = "### Bugfixes"
showcontent = true

[[tool.towncrier.type]]
directory = "security"
name = "### Security Improvements"
showcontent = true

[[tool.towncrier.type]]
directory = "internal"
name = "### Internal Changes - for Trin Contributors"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "### Improved Documentation"
showcontent = true
